class Prescription:
    """
    Represents a medical prescription generated by a doctor for a patient.
    """
    def __init__(self, prescription_id, appointment, medications, instructions):
        # Private attributes (Encapsulation)
        self.__prescription_id = prescription_id
        self.__appointment = appointment
        self.__medications = medications  # List of medications e.g., ["Aspirin", "Ibuprofen"]
        self.__instructions = instructions
        
    def display_details(self):
        """Returns string representation of the prescription."""
        meds = ", ".join(self.__medications)
        patient_name = self.__appointment.patient.name
        doctor_name = self.__appointment.doctor.name
        return f"Prescription ID: {self.__prescription_id} | For: {patient_name} | By: Dr. {doctor_name} | Meds: {meds} | Instructions: {self.__instructions}"
